/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.frames.event;

/**
 *
 * @author Francisco Miguel Carrasquilla Rodríguez-Córdoba
 * <afcarrasquilla@iesfranciscodelosrios.es>
 */
public class ListEventFrame extends javax.swing.JFrame {

    /**
     * Creates new form ListEventFrame
     */
    public ListEventFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        BAdd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BEdit = new javax.swing.JButton();
        BDelete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BSave = new javax.swing.JButton();
        BCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Registros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        BAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        BAdd.setText("Nuevo");
        BAdd.setToolTipText("");
        BAdd.setBorderPainted(false);
        BAdd.setContentAreaFilled(false);
        BAdd.setFocusable(false);
        BAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });
        jToolBar1.add(BAdd);
        jToolBar1.add(jSeparator1);

        BEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        BEdit.setText("Editar");
        BEdit.setBorderPainted(false);
        BEdit.setContentAreaFilled(false);
        BEdit.setEnabled(false);
        BEdit.setFocusable(false);
        BEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        jToolBar1.add(BEdit);

        BDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        BDelete.setText("Eliminar");
        BDelete.setBorderPainted(false);
        BDelete.setContentAreaFilled(false);
        BDelete.setEnabled(false);
        BDelete.setFocusable(false);
        BDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(BDelete);
        jToolBar1.add(jSeparator2);

        BSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N
        BSave.setText("Guardar");
        BSave.setBorderPainted(false);
        BSave.setContentAreaFilled(false);
        BSave.setEnabled(false);
        BSave.setFocusable(false);
        BSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(BSave);

        BCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        BCancel.setText("Cancelar");
        BCancel.setBorderPainted(false);
        BCancel.setContentAreaFilled(false);
        BCancel.setEnabled(false);
        BCancel.setFocusable(false);
        BCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelActionPerformed(evt);
            }
        });
        jToolBar1.add(BCancel);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel1.setLayout(new java.awt.BorderLayout());

        Registros.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Registros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Registros))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddActionPerformed
        tabla.clearSelection();
        Details.setHeadquarter(null);
        Details.loadData();
        Details.setEdit(true);
        activateButtonsSave(true);
    }//GEN-LAST:event_BAddActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        try {
            Headquarter headquarter = getSelectedHeadquarter();
            Details.setHeadquarter(headquarter);
            Details.setEnabled(true);
            Details.setEdit(true);
            Details.loadData();
            activateButtonsSave(true);
        } catch (DAOException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_BEditActionPerformed

    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Seguro que quieres borrar "
            + "esta sede?", "Borrar Sede", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
        try {
            Headquarter headquarter = getSelectedHeadquarter();
            manager.getHeadquarterDAO().delete(headquarter);
            getData();
        } catch (DAOException ex) {
            ex.getMessage();
        }
        }
    }//GEN-LAST:event_BDeleteActionPerformed

    private void BSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSaveActionPerformed
        try {
            if (Details.checkData()) {
                Details.saveData();
                Headquarter headquarter = Details.getHeadquarter();
                if (headquarter.getId() == null) {
                    manager.getHeadquarterDAO().insert(headquarter);
                } else {
                    manager.getHeadquarterDAO().modify(headquarter);
                }
                Details.setHeadquarter(null);
                Details.setEdit(false);
                Details.loadData();
                tabla.clearSelection();
                activateButtonsSave(false);
                getData();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Por favor rellene "
                    + "todos los campos", "Error datos incompletos",
                    JOptionPane.OK_OPTION);
            }
        } catch (DAOException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_BSaveActionPerformed

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelActionPerformed
        Details.setHeadquarter(null);
        Details.setEdit(false);
        Details.loadData();
        tabla.clearSelection();
        activateButtonsSave(false);
    }//GEN-LAST:event_BCancelActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListEventFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BCancel;
    private javax.swing.JButton BDelete;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BSave;
    private javax.swing.JLabel Registros;
    private javax.swing.JTable Table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}

